version: "3.2"
services:
  redis:
    container_name: redis
    image: "redis:alpine"
    ports:
      - "6379:6379"
    command: redis-server "/usr/local/etc/redis/redis.conf"
    volumes:
      - $PWD/conf/redis.conf:/usr/local/etc/redis/redis.conf
  mongodb:
    container_name: mongodb
    image: "mongo:latest"
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - $HOME/data:/data/db